name: CI

on:
  push:

jobs:
  package-mypy:
    name: "Package: mypy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libertai_agents
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: './libertai_agents/pyproject.toml'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Run mypy
        run: poetry run mypy --show-column-numbers --show-absolute-path --no-pretty .

  package-ruff:
    name: "Package: ruff"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libertai_agents
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: './libertai_agents/pyproject.toml'
          cache: 'poetry'
      - name: Install dependencies
        run: pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github
